title: Dirigo RC
description: Maine running club founded in 2002.
url: "https://dirigorc.com"
exclude:
  - .bundle/
  - .jekyll-cache/
  - .sass-cache/
  - dirigo-email-ingest/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
plugins:
  - jekyll-paginate
collections:
  events:
    output: false
paginate: 6
paginate_path: "/updates/page/:num/"
defaults:
  - scope:
      path: ""
    values:
      layout: null
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: null
      output: false
  - scope:
      path: "_events"
      type: "events"
    values:
      layout: null
      output: false
